coin/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.apps import apps
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

import autocomplete_light
autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield url(
                    r'^{}/'.format(prefix),
                    include(pats, namespace=prefix))

urlpatterns = patterns(
    '',
    url(r'^$', 'coin.members.views.index', name='home'),

    url(r'^isp.json$', isp_json),
    url(r'^members/', include('coin.members.urls', namespace='members')),
    url(r'^billing/', include('coin.billing.urls', namespace='billing')),
    url(r'^subscription/', include('coin.offers.urls', namespace='subscription')),

    url(r'^admin/', include(admin.site.urls)),

    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^feed/(?P<feed_name>.+)', views.feed, name='feed'),

    url(r'^autocomplete/', include('autocomplete_light.urls')),

)

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())

hardware_provisioning/urls.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.loan_list, name='loan-list'),
    url(r'^items/list$', views.item_list, name='item-list'),
    url(r'^items/(?P<pk>[0-9]+)/borrow$', views.item_borrow, name='item-borrow'),
    url(r'^(?P<pk>[0-9]+)/return$', views.loan_return, name='loan-return'),
    url(r'^(?P<pk>[0-9]+)/transfer$', views.loan_transfer, name='loan-transfer'),
    url(r'^(?P<pk>[0-9]+)$', views.loan_detail, name='loan-detail'),
]

vpn/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import patterns, url

from .views import VPNView, VPNGeneratePasswordView, get_graph

urlpatterns = patterns(
    '',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
)

hardware_provisioning/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.utils import timezone

from .fields import MACAddressField


class ItemType(models.Model):
    name = models.CharField(max_length=100, verbose_name='nom')

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = 'type d’objet'
        verbose_name_plural = 'types d’objet'


class ItemQuerySet(models.QuerySet):
    def _get_borrowed_pks(self):
        return Loan.objects.running().values_list('item', flat=True)

    def available(self):
        return self.exclude(
            pk__in=self._get_borrowed_pks()).exclude(deployed=True)

    def borrowed(self):
        return self.filter(pk__in=self._get_borrowed_pks())

    def deployed(self):
        return self.filter(deployed=True)

    def unavailable(self):
        """ deployed or borrowed
        """
        return self.filter(
            Q(pk__in=self._get_borrowed_pks()) |
            Q(deployed=True))


class Item(models.Model):
    type = models.ForeignKey(ItemType, verbose_name='type de matériel',
                             related_name='items')
    designation = models.CharField(max_length=100, verbose_name='désignation')
    storage = models.ForeignKey(
        'Storage', related_name='items',
        verbose_name='Lieu de stockage',
        null=True, blank=True,
        help_text='Laisser vide si inconnu')
    mac_address = MACAddressField(
        verbose_name='adresse MAC',
        blank=True, null=True, unique=True,
        help_text="préférable au n° de série si possible")
    serial = models.CharField(
        verbose_name='N° de série',
        max_length=250, blank=True, null=True, unique=True,
        help_text='ou toute autre référence unique')
    buy_date = models.DateField(verbose_name='date d’achat' , blank=True , null=True)
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='Propriétaire',
        related_name='items',
        null=True, blank=True,
        help_text="dans le cas de matériel n'appartenant pas à l'association")
    deployed = models.BooleanField(verbose_name='déployé', default=False,
                                   help_text='Cocher si le matériel est en production')
    comment = models.TextField(verbose_name='commentaire', blank=True,
                               null=True)

    objects = ItemQuerySet().as_manager()

    def __unicode__(self):
        return self.designation

    def save(self, *args, **kwargs):
        # workaround for unique=True, null=True
        # see https://code.djangoproject.com/ticket/4136#comment:33
        self.mac_address = self.mac_address or None
        self.serial = self.serial or None

        return super(Item, self).save(*args, **kwargs)

    def get_current_loan(self):
        """
        Returns the current Loan for this Item, if exists, or None.
        """
        try:
            return self.loans.get(loan_date_end__isnull=True)
        except Loan.DoesNotExist:
            return None

    def is_available(self):
        """
        Returns the status of the Item. If a running loan exists,
        or if the item is deployed, returns False (else True).
        """
        return (not self.deployed) and (not self.loans.running().exists())
    is_available.boolean = True
    is_available.short_description = 'disponible'

    def get_mac_and_serial(self):
        mac = self.mac_address
        serial = self.serial
        if mac and serial:
            return "{} / {}".format(mac, serial)
        else:
            return mac or serial or ''

    class Meta:
        verbose_name = 'objet'

    def give_back(self, storage=None):
        self.storage = storage
        self.save()
        self.loans.running().update(
            loan_date_end=timezone.now())


class LoanQuerySet(models.QuerySet):

    @staticmethod
    def _running_filter():
        return (
            models.Q(loan_date_end__gt=timezone.now()) |
            models.Q(loan_date_end__isnull=True))

    def running(self):
        return self.filter(self._running_filter())

    def finished(self):
        return self.exclude(self._running_filter())


class Loan(models.Model):
    item = models.ForeignKey(Item, verbose_name='objet', related_name='loans')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='membre',
                             related_name='loans')
    loan_date = models.DateTimeField(verbose_name='date de prêt')
    loan_date_end = models.DateTimeField(verbose_name='date de fin de prêt',
                                     null=True, blank=True)
    notes = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return 'prêt de {item} à {user}'.format(
            item=self.item, user=self.user)

    def get_mac_and_serial(self):
        return self.item.get_mac_and_serial()

    get_mac_and_serial.short_description = "Adresse MAC / n° de série"

    def user_can_close(self, user):
        return (not self.item.is_available()) and (self.user == user)

    def is_running(self):
        return not self.loan_date_end or self.loan_date_end > timezone.now()
    is_running.boolean = True
    is_running.short_description = 'En cours ?'

    class Meta:
        verbose_name = 'prêt d’objet'
        verbose_name_plural = 'prêts d’objets'

    objects = LoanQuerySet().as_manager()


class Storage(models.Model):
    name = models.CharField(max_length=100, verbose_name='nom')
    notes = models.TextField(
        blank=True,
        help_text='Lisible par tous les adhérents')

    def __unicode__(self):
        return self.name

    def items_count(self):
        return self.items.count()
    items_count.short_description = 'Nb. items stockés'

    class Meta:
        verbose_name = 'lieu de stockage'
        verbose_name_plural = 'lieux de stockage'

hardware_provisioning/forms.py
# -*- coding: utf-8 -*-

from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.db.models import Q
from django import forms

from .models import Storage
from .validators import validate_future_date

User = get_user_model()


class LoanDeclareForm(forms.Form):
    loan_date_end = forms.DateField(
        label='Date de retour prévue',
        required=False,
        validators=[validate_future_date],
        input_formats=['%d/%m/%Y'],
        help_text='laisser vide si non planifié',
        widget=forms.TextInput(
            attrs={'type': 'date', 'placeholder': 'JJ/MM/AAAA'}))


class LoanReturnForm(forms.Form):
    storage = forms.ModelChoiceField(
        label='Dans quel lieu de stockage ai-je remis le matériel ?',
        required=False,
        queryset=Storage.objects.all(), empty_label='Je ne sais pas')


class LoanTransferForm(forms.Form):
    target_user = forms.CharField(
        max_length=100,
        label='Adhérent',
        help_text='email, pseudonyme ou numéro de l\'adhérent',
    )

    def clean_target_user(self):
        value = self.cleaned_data['target_user']
        result = User.objects.filter(
            Q(email__iexact=value)
            | Q(pk__iexact=value)
            | Q(nickname__iexact=value)
            | Q(username__iexact=value)
        )
        if result.count() > 1:
            raise ValidationError(
                "La recherche retourne plus d'un adhérent")
        elif result.count() < 1:
            raise ValidationError(
                "Aucun adhérent ne correspond à cette recherche")

        return result.first()

hardware_provisioning/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals


from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.utils import timezone

from .forms import LoanDeclareForm, LoanTransferForm, LoanReturnForm
from .models import Item, Loan


@login_required
def item_list(request):
    items = Item.objects.all().order_by('storage', 'type', 'designation')

    # FIXME: suboptimal
    items = [i for i in items.filter() if i.is_available()]
    return render(request, 'hardware_provisioning/item_list.html', {
        'items': items,
    })


@login_required
def item_borrow(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if not item.is_available():
        return HttpResponseForbidden('Item non disponible')

    if request.method == 'POST':
        form = LoanDeclareForm(request.POST)
        if form.is_valid():
            loan = Loan.objects.create(
                item=item,
                loan_date=timezone.now(),
                loan_date_end=form.cleaned_data['loan_date_end'],
                user=request.user,
            )
            messages.success(
                request, "Emprunt de {} ({}) enregistré".format(
                    item.designation, item.type))
            if not loan.loan_date_end:
                messages.warning(
                    request,
                    "N'oubliez pas de notifier le retour de l'objet le temps venu")
            return redirect(reverse('hardware_provisioning:loan-list'))
    else:
        form = LoanDeclareForm()

    return render(request, 'hardware_provisioning/item_borrow.html', {
        'item': item,
        'form': form,
    })


@login_required
def loan_return(request, pk):
    loan = get_object_or_404(Loan, pk=pk)

    if not loan.user_can_close(request.user):
        return HttpResponseForbidden('Non autorisé')

    if request.method == 'POST':
        form = LoanReturnForm(request.POST)
        if form.is_valid():
            messages.success(
                request,
                'Le matériel {} a été marqué comme rendu'.format(
                    loan.item))
            loan.item.give_back(form.cleaned_data['storage'])
            return redirect(reverse('hardware_provisioning:loan-list'))
    else:
        form = LoanReturnForm()

    return render(request, 'hardware_provisioning/return.html', {
        'loan': loan,
        'form': form,
    })


@login_required
def loan_transfer(request, pk):
    """ Transfer something loaned to another member
    """
    old_loan = get_object_or_404(Loan, pk=pk)

    if not old_loan.user_can_close(request.user):
        return HttpResponseForbidden()

    if request.method == 'POST':
        form = LoanTransferForm(request.POST)
        if form.is_valid():
            old_loan.item.give_back()
            Loan.objects.create(
                user=form.cleaned_data['target_user'],
                loan_date=timezone.now(),
                item=old_loan.item)
            messages.success(
                request,
                "Le matériel {} a été transféré à l'adhérent \"{}\"".format(
                    old_loan.item,
                    form.data['target_user']))
            return redirect(reverse('hardware_provisioning:loan-list'))

    else:
        form = LoanTransferForm()

    return render(request, 'hardware_provisioning/transfer.html', {
        'form': form,
        'loan': old_loan,
    })


@login_required
def loan_list(request):
    view = 'old' if 'old' in request.GET else ''

    if view == 'old':
        loans = request.user.loans.finished().order_by('-loan_date_end')
    else:
        loans = request.user.loans.running()

    return render(request, 'hardware_provisioning/list.html', {
        'loans': loans,
        'view': view,
    })


@login_required
def loan_detail(request, pk):
    return render(request, 'hardware_provisioning/detail.html', {})

hardware_provisioning/templates/hardware_provisioning/base.html
{% extends "base.html" %}

{% load static %}

{% block extra_css %}<link rel="stylesheet" href="{% static "hardware_provisioning/css/local.css" %}">{% endblock %}

hardware_provisioning/templates/hardware_provisioning/item_borrow.html
{% extends 'hardware_provisioning/base.html' %}

{% block content %}

<p>Je déclare emprunter le matériel <strong>{{item }} ({{ item.type }}</strong>) à compter de ce jour.</p>


<form method='post'>{% csrf_token %}
{{ form.as_p }}
    <input class="success button" type="submit"
           value="Oui oui, c'est bien ça."/>
</form>

{% endblock %}

hardware_provisioning/templates/hardware_provisioning/item_list.html
{% extends "hardware_provisioning/base.html" %}

{% block content %}
<h2>J'emprunte à l'association…</h2>

<table>
    <thead>
        <tr>
            <th>Type de matériel</th>
            <th>Désignation</th>
            <th>Dépôt</th>
            <th>Addr. MAC</th>
            <th>Num. de série</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody>
       {% for i in items %}
        <tr>
            <td>{{ i.type }}</td>
            <td>{{ i.designation }}</td>
            <td>{{ i.storage|default:'inconnu' }}</td>
            <td>{{ i.mac_address|default:'n/a' }}</td>
            <td>{{ i.serial|default:'n/a' }}</td>
            <td class="actions">
                <div class="button-group">
                  <a href="{% url 'hardware_provisioning:item-borrow' pk=i.pk %}" class="small button">
                     <i class="fa fa-exchange"></i>&nbsp;Emprunter
                 </a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>

</table>
{% endblock %}

hardware_provisioning/templates/hardware_provisioning/list.html
{% extends "hardware_provisioning/base.html" %}

{% block content %}
{% if view  == 'old' %}
<h2>L'association m'a prêté…</h2>
{% else %}
<h2>L'association me prête…</h2>
{% endif %}
{% for message in messages %}
<div class="message {{ message.tags }}">{{ message }}</div>
{% endfor %}

<p>
    <a href="{% url 'hardware_provisioning:item-list' %}"
       class="button pre-table-action success">
        <i class="fa fa-plus"></i> Déclarer un emprunt
    </a>
</p>

<table id="member_loans" class="full-width">
    <thead>
        <tr>
            <th>Type de matériel</th>
            <th>Matériel prêté</th>
            <th>Date de prêt</th>
            {% if view == 'old' %}<th>Date retour</th>{% endif %}
            <th>Addr. MAC</th>
            <th>Num. de série</th>
            {% if view != 'old' %}<th>Actions</th>{% endif %}
        </tr>
    </thead>
    <tbody>
        {% for loan in loans %}
        <tr>
            <td>{{ loan.item.type }}</td>
            <td>{{ loan.item }}</a></td>
            <td>{{ loan.loan_date }}</td>
            {% if view == 'old' %}<td>{{ loan.loan_date_end }}</td>{% endif %}
            <td>{{ loan.item.mac_address|default:"n/a" }}</td>
            <td>{{ loan.item.serial|default:"n/a" }}</td>
            {% if view != 'old' %}
            <td class="actions">
              <div class="button-group">
                  <a href="{% url 'hardware_provisioning:loan-return' pk=loan.pk %}" class="small button">
                     <i class="fa fa-times"></i>&nbsp;Rendre
                 </a>
                <a href="{% url 'hardware_provisioning:loan-transfer' pk=loan.pk %}" class="small button">
                   <i class="fa fa-exchange"></i> Transférer
                </a>
              </div>
            </td>
            {% endif %}
        </tr>
        {% empty %}
        <tr class="placeholder"><td colspan="6">… rien du tout !</td></tr>
        {% endfor %}
    </tbody>
</table>

<p class="list-filter">
    {% if view == 'old' %}
    <a href="./">Afficher les prêts en cours</a>
    {% else %}
    <a href="?old">Afficher l'historique de prêt</a>
    {% endif %}
</p>
{% endblock %}

hardware_provisioning/templates/hardware_provisioning/return.html
{% extends "hardware_provisioning/base.html" %}

{% block content %}
<h2>Retour de matériel</h2>
<p>
    J'ai rendu le matériel <strong>{{loan.item }} ({{ loan.item.type }}</strong>) a l'association ce jour.
</p>
<form method='post'>{% csrf_token %}
  {{ form.as_p }}
  <input class="success button" type="submit"
         value="Oui oui, c'est bien ça."/>
</form>
{% endblock %}

hardware_provisioning/templates/hardware_provisioning/transfer.html
{% extends "hardware_provisioning/base.html" %}

{% block content %}
<h2>Transfert de matériel</h2>
<p>
    J'ai passé aujourd'hui le matériel <strong>{{  loan.item }}
    ({{ loan.item.type }}</strong>) a un autre adhérent :
</p>
<form method="post">{% csrf_token %}
  <p>
    <input id="id_target_user"
           name="target_user"
           type="text" placeholder="{{ form.target_user.help_text }}"/>
    {{ form.target_user.errors }}
  <input class="success button" type="submit"
         value="Oui oui, c'est bien ça."/>
</form>
{% endblock %}